riddles = {
    1: {"riddle": "I am essential for life, yet invisible. I fill your lungs and help you thrive. What am I?", "answer": "oxygen"},
    2: {"riddle": "I’m found in fruits, veggies, and the sun, keeping your bones strong when my work is done. What am I?", "answer": "vitamin d"},
    3: {"riddle": "I beat over 100,000 times a day, pumping blood to keep you on your way. What am I?", "answer": "heart"},
    4: {"riddle": "I am a mineral you must not lack, found in leafy greens and a tasty snack. What am I?", "answer": "iron"},
    5: {"riddle": "I am the body's way of resting and repair, you do me every night without a care. What am I?", "answer": "sleep"},
    6: {"riddle": "I can make you feel dizzy, faint, or cold, lack of me is not for the bold. What am I?", "answer": "blood"},
    7: {"riddle": "I protect you from diseases and fight germs; you can find me in vaccines on terms. What am I?", "answer": "immune system"},
    8: {"riddle": "I’m essential to survive, two-thirds of me make up your size. What am I?", "answer": "water"},
    9: {"riddle": "I’m red and round, and doctors say one of me a day keeps them away. What am I?", "answer": "apple"},
    10: {"riddle": "Without me, you can't run or leap, I carry oxygen from head to feet. What am I?", "answer": "haemoglobin"},
    11: {"riddle": "I’m the key to strong bones, in dairy and greens I’m known. What am I?", "answer": "calcium"},
    12: {"riddle": "I help you see in the dark of night, found in carrots and shining bright. What am I?", "answer": "vitamin a"},
    13: {"riddle": "I’m needed for your heart and nerves, I’m in bananas and many herbs. What am I?", "answer": "potassium"},
    14: {"riddle": "I keep your skin safe from harmful rays, with a touch of me on sunny days. What am I?", "answer": "sunscreen"},
    15: {"riddle": "I measure the force of your blood’s flow, high numbers can mean health is low. What am I?", "answer": "blood pressure"},
    16: {"riddle": "I’m needed when you're sick or sore, given in pills, shots, and sometimes more. What am I?", "answer": "medicine"},
    17: {"riddle": "I’m a protein that helps you heal, covering cuts and wounds like steel. What am I?", "answer": "collagen"},
    18: {"riddle": "I carry nutrients and oxygen in, and waste out, within my spin. What am I?", "answer": "blood vessels"},
    19: {"riddle": "I can harm your lungs and your air, released by factories into the air. What am I?", "answer": "pollution"},
    20: {"riddle": "I help prevent diseases when you’re young, and in schools, I am often sung. What am I?", "answer": "vaccination"},
    21: {"riddle": "I’m a shot given for protection, I stop infection from gaining direction. What am I?", "answer": "vaccine"},
    22: {"riddle": "I am a daily habit to keep your mouth clean, you do me with paste and a machine. What am I?", "answer": "brushing teeth"},
    23: {"riddle": "I can make you run faster and grow strong, when you do me, your health won’t go wrong. What am I?", "answer": "exercise"},
    24: {"riddle": "I tell you how much heat you hold, whether you’re feverish or too cold. What am I?", "answer": "thermometer"},
    25: {"riddle": "I’m part of your body that fights disease, a white cell army that never sleeps. What am I?", "answer": "white blood cells"},
    26: {"riddle": "I help you relax, and sometimes you dream, eight hours a night is the common theme. What am I?", "answer": "sleep"},
    27: {"riddle": "I’m a fruit that fights sickness with vitamin C, orange and round, I grow on a tree. What am I?", "answer": "orange"},
    28: {"riddle": "I’m a fluid in your body that removes waste, kidneys help me flow at a steady pace. What am I?", "answer": "urine"},
    29: {"riddle": "I’m essential for growth and repair, found in meats, nuts, and in the air. What am I?", "answer": "protein"},
    30: {"riddle": "I’m a sugar your brain and muscles need, I give you energy at great speed. What am I?", "answer": "glucose"},
    31: {"riddle": "I’m a mineral that makes your teeth shine, found in water and toothpaste, I keep you fine. What am I?", "answer": "fluoride"},
    32: {"riddle": "I help you run and play each day, I’m a nutrient that keeps hunger away. What am I?", "answer": "carbohydrate"},
    33: {"riddle": "I’m a liquid gold your body can’t lack, I keep you warm and help your back. What am I?", "answer": "fat"},
    34: {"riddle": "I’m a sign you need to hydrate, when your mouth feels dry and not so great. What am I?", "answer": "thirst"},
    35: {"riddle": "I’m a sharp, sudden pain in your head, sometimes from stress, sometimes dread. What am I?", "answer": "headache"},
    36: {"riddle": "I cause you to cough, sneeze, and blow, but with some rest, I’ll eventually go. What am I?", "answer": "cold"},
    37: {"riddle": "I’m a break from work, a time to rest, with me, your body performs its best. What am I?", "answer": "vacation"},
    38: {"riddle": "I’m a condition of blood sugar high, a careful diet keeps me nigh. What am I?", "answer": "diabetes"},
    39: {"riddle": "I’m a virus that affects the liver, but with vaccines, the risk is thinner. What am I?", "answer": "hepatitis"},
    40: {"riddle": "I help you fight infections and the flu, found in tablets or a drink for you. What am I?", "answer": "vitamin c"},
    41: {"riddle": "I’m a condition that makes breathing tough, avoid pollution to stay good enough. What am I?", "answer": "asthma"},
    42: {"riddle": "I help detect disease through a scan, pictures of the body, I create a plan. What am I?", "answer": "x-ray"},
    43: {"riddle": "I’m a test done to see your heart’s pace, beating fast or slow, I set the trace. What am I?", "answer": "ecg"},
    44: {"riddle": "I’m a fruit with a tropical taste, I help digestion and never go to waste. What am I?", "answer": "pineapple"},
    45: {"riddle": "I’m a gas your body releases, after you eat and your stomach increases. What am I?", "answer": "carbon dioxide"},
    46: {"riddle": "I’m a condition where the eyes can’t see far, glasses or surgery can raise the bar. What am I?", "answer": "myopia"},
    47: {"riddle": "I’m an infection that affects your skin, itching and redness, I might begin. What am I?", "answer": "eczema"},
    48: {"riddle": "I’m the first response when someone is hurt, bandages, CPR, I’m always alert. What am I?", "answer": "first aid"},
    49: {"riddle": "I’m an addiction to a harmful smoke, inhaling me can make you choke. What am I?", "answer": "smoking"},
    50: {"riddle": "I’m a molecule that gives your body light, used in cells to produce energy right. What am I?", "answer": "atp"},
}


